object fmAbout: TfmAbout
  Left = 0
  Top = 0
  BorderStyle = bsToolWindow
  Caption = 'fmAbout'
  ClientHeight = 337
  ClientWidth = 401
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poScreenCenter
  PixelsPerInch = 96
  TextHeight = 13
end
